---
- name: Copy adguardhome service config
  ansible.builtin.copy:
    src: adguardhome/
    dest: /services/adguardhome

- name: Write Caddy env file
  ansible.builtin.template:
    src: caddy.env.j2
    dest: /services/adguardhome/caddy.env

- name: Create and deploy adguardhome docker compose services
  community.docker.docker_compose_v2:
    project_src: /services/adguardhome
