services:
  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    volumes:
        - ./work:/opt/adguardhome/work
        - ./conf:/opt/adguardhome/conf
    ports:
      - 3000:3000
      - 53:53
      - 53:53/udp
      - 853:853
      - 67:67/udp
      - 68:68/udp
    image: adguard/adguardhome
