---
- name: Install k3s on Nebula cluster
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  tasks:
    - name: Run k3s-uninstall
      ansible.builtin.shell:
        cmd: /usr/local/bin/k3s-uninstall.sh
