---
- name: Install k3s on Nebula cluster
  hosts: nebula
  gather_facts: yes
  become: yes
  roles:
    - role: k3s.orchestration.site

- name: Update kubectl context
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get kubeconfig from k3s server
      ansible.builtin.shell:
        cmd: |
          ssh -i keys/nebula_id_rsa -o StrictHostKeyChecking=no astro@nebula01.local "sudo cat /etc/rancher/k3s/k3s.yaml"
      register: kubeconfig_content
    - name: Write kubeconfig to local file
      ansible.builtin.copy:
        content: "{{ kubeconfig_content.stdout }}"
        dest: ~/.kube/config
        mode: '0644'
      when: kubeconfig_content.stdout is defined
