services:
    adguardhome:
        container_name: adguardhome
        restart: unless-stopped
        volumes:
            - ./work:/opt/adguardhome/work
            - ./conf:/opt/adguardhome/conf
        network_mode: host
        image: adguard/adguardhome
