---
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    networks:
      - caddy
    volumes:
      - /mnt/hdd/syncthing/config:/config
      - /mnt/hdd/syncthing/data:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

networks:
  caddy:
    external: true
