apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.15.2/crd.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.15.2/system-upgrade-controller.yaml
  - k3s-server-upgrade-plan.yaml
  - k3s-agent-upgrade-plan.yaml
  - ubuntu-os-upgrade-plan.yaml
  - versioner-serviceaccount.yaml
  - versioner-role.yaml
  - versioner-cronjob.yaml
