apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: ubuntu-os-upgrade
  namespace: system-upgrade
spec:
  version: "2025-05-19"
  concurrency: 1
  cordon: true
  drain:
    timeout: 900000000000 # why did they make this nanoseconds
    deleteLocalData: true
    force: true
    disableEviction: true
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - key: ubuntu-upgrades
        operator: NotIn
        values: ["disabled"]
  upgrade:
    image: ubuntu:24.04
    command: [bash, -c]
    args:
      - |
        set -euo pipefail
        APT_OPTS='-o Acquire::Retries=3 -o Acquire::ForceIPv4=true'
        echo "[suc] ubuntu-os-upgrade $(date --iso-8601=seconds)"

        chroot /host apt-get $APT_OPTS install -y update-notifier-common

        chroot /host bash -ceu "
          apt-get ${APT_OPTS} clean
          apt-get ${APT_OPTS} update
          apt-get ${APT_OPTS} dist-upgrade -y --fix-missing
        "

        if [ -f /host/var/run/reboot-required ]; then
          echo '[suc] reboot required – scheduling reboot'
          (nsenter --mount=/host/proc/1/ns/mnt -- /sbin/reboot -f &)
        else
          echo '[suc] no reboot required'
        fi
        exit 0                     # job must end with exit code 0
