apiVersion: batch/v1
kind: CronJob
metadata:
  name: ubuntu-os-upgrade-versioner
  namespace: system-upgrade
spec:
  schedule: "0 3 * * *" # Run at 3am every day
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: versioner
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  DATE=$(date +%Y-%m-%d)
                  kubectl patch plan ubuntu-os-upgrade -n system-upgrade --type=merge -p "{\"spec\":{\"version\":\"$DATE\"}}"
