namespace: cert-manager

secretGenerator:
  - name: porkbun-key
    envs:
      - .env.secret

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.5/cert-manager.yaml
  - issuer.yaml
  - porkbun-webhook/rbac.yaml
  - extension-apiserver-authentication-reader.yaml
  - porkbun-webhook-auth-reader.yaml

helmGlobals:
  chartHome: porkbun-webhook/deploy

helmCharts:
  - name: porkbun-webhook
    releaseName: porkbun-webhook
    namespace: cert-manager

    valuesInline:
      groupName: quiet.ooo
      nameOverride: porkbun-webhook
      fullnameOverride: porkbun-webhook
