services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    networks:
      - caddy
    volumes:
      - ./data:/app/data

networks:
  caddy:
    external: true
