apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pocket-id

resources:
  - namespace.yaml
  - serviceAccount.yaml
  - configMap.yaml
  - service.yaml
  - statefulSet.yaml
  - ingress.yaml
